name: Deploy to Azure Container App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: appservicedemoa.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: appservicedemoa.azurecr.io/dotnetcoreapp:${{ github.sha }}

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Container App
      uses: azure/CLI@v1
      with:
        azcliversion: 2.55.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update \
          --name app01 \
          --resource-group con-demo \
          --image appservicedemoa.azurecr.io/dotnetcoreapp:${{ github.sha }}